# NOTE: Generated By HttpRunner v3.1.4
# FROM: ..\testcases\wechat_section_select.yml





from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseWechatSectionSelect(HttpRunner):

    

    config = Config("查找部门").export(*['parentid'])

    teststeps = [
        
            Step(RunRequest("获取部门列表").get("${rand_yaml_data(host)}/cgi-bin/department/list").with_params(**{'access_token': '${rand_yaml_data(access_token)}'}).with_headers(**{'User-Agent': 'PostmanRuntime/7.26.10'}).extract().with_jmespath('body.department[0].id', 'parentid').validate().assert_equal("status_code", 200).assert_equal('headers."Content-Type"', "application/json; charset=UTF-8").assert_equal("body.errcode", 0).assert_equal("body.errmsg", "ok").assert_contains("body.department[0]", "id")),
        
    ]

if __name__ == "__main__":
    TestCaseWechatSectionSelect().test_start()
