# NOTE: Generated By HttpRunner v3.1.4
# FROM: ..\testcases\wechat_section_alter.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseWechatSectionAlter(HttpRunner):

    config = Config("修改部门信息").variables(
        **{
            "id": "${rand_yaml_data(subdivision_id)}",
            "parentid": "${rand_yaml_data(parentid)}",
        }
    )

    teststeps = [
        Step(
            RunRequest("更新部门信息")
            .post("${rand_yaml_data(host)}/cgi-bin/department/update")
            .with_params(**{"access_token": "${rand_yaml_data(access_token)}"})
            .with_headers(**{"Content-Type": "application/json"})
            .with_json(
                {
                    "id": "${id}",
                    "name": "修改北京研发中心",
                    "name_en": "RDBJ",
                    "order": 1,
                    "parentid": "${parentid}",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json; charset=UTF-8")
            .assert_equal("body.errcode", 0)
            .assert_equal("body.errmsg", "updated")
        ),
    ]


if __name__ == "__main__":
    TestCaseWechatSectionAlter().test_start()
