# NOTE: Generated By HttpRunner v3.1.4
# FROM: ..\testcases\wechat_section_delect.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseWechatSectionDelect(HttpRunner):

    config = Config("删除相关部门")

    teststeps = [
        Step(
            RunRequest("删除部门")
            .get("${rand_yaml_data(host)}/cgi-bin/department/delete")
            .with_params(
                **{
                    "access_token": "${rand_yaml_data(access_token)}",
                    "id": "${rand_yaml_data(subdivision_id)}",
                }
            )
            .with_headers(
                **{
                    "Postman-Token": "38e3a0a4-ad0d-4a45-9877-9102dad47fcc",
                    "User-Agent": "PostmanRuntime/7.26.10",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json; charset=UTF-8")
            .assert_equal("body.errcode", 0)
            .assert_equal("body.errmsg", "deleted")
        ),
    ]


if __name__ == "__main__":
    TestCaseWechatSectionDelect().test_start()
