# NOTE: Generated By HttpRunner v3.1.4
# FROM: ..\testcases\wechat_section_create.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseWechatSectionCreate(HttpRunner):

    config = Config("创建部门").variables(
        **{"id": 2, "name": "北京研发中心", "name_en": "RDBJ", "order": 1}
    )

    teststeps = [
        Step(
            RunRequest("创建部门")
            .post("${rand_yaml_data(host)}/cgi-bin/department/create")
            .with_params(**{"access_token": "${rand_yaml_data(access_token)}"})
            .with_headers(**{"Content-Type": "application/json"})
            .with_json(
                {
                    "id": "${rand_yaml_data(subdivision_id)}",
                    "name": "${name}",
                    "name_en": "${name_en}",
                    "order": "${order}",
                    "parentid": "${rand_yaml_data(parentid)}",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json; charset=UTF-8")
            .assert_equal("body.errcode", 0)
            .assert_equal("body.errmsg", "created")
            .assert_equal("body.id", "${id}")
        ),
    ]


if __name__ == "__main__":
    TestCaseWechatSectionCreate().test_start()
