# NOTE: Generated By HttpRunner v3.1.4
# FROM: ..\testcases\wechat_access_token.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseWechatAccessToken(HttpRunner):

    config = Config("查找部门")

    teststeps = [
        Step(
            RunRequest("获取access_token")
            .get("${rand_yaml_data(host)}/cgi-bin/gettoken")
            .with_params(
                **{
                    "corpid": "${rand_yaml_data(corpid)}",
                    "corpsecret": "${rand_yaml_data(corpsecret)}",
                }
            )
            .with_headers(
                **{
                    "Postman-Token": "60602b56-73b7-4ea7-b6cc-384a0d8b78fa",
                    "User-Agent": "PostmanRuntime/7.26.10",
                }
            )
            .extract()
            .with_jmespath("body.access_token", "access_token")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json; charset=UTF-8")
            .assert_equal("body.errcode", 0)
            .assert_equal("body.errmsg", "ok")
            .assert_equal("body.expires_in", 7200)
        ),
    ]


if __name__ == "__main__":
    TestCaseWechatAccessToken().test_start()
